import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';

function parseCSV(csvText) {
  const lines = [];
  let row = [""];
  let insideQuote = false;

  for (let i = 0; i < csvText.length; i++) {
    const char = csvText[i];
    const nextChar = csvText[i + 1];

    if (char === '"') {
      if (insideQuote && nextChar === '"') {
        row[row.length - 1] += '"';
        i++;
      } else {
        insideQuote = !insideQuote;
      }
    } else if (char === ',' && !insideQuote) {
      row.push('');
    } else if ((char === '\r' || char === '\n') && !insideQuote) {
      if (char === '\r' && nextChar === '\n') {
        i++;
      }
      lines.push(row);
      row = [""];
    } else {
      row[row.length - 1] += char;
    }
  }
  if (row.length > 1 || row[0] !== '') {
    lines.push(row);
  }
  return lines.filter(r => r.length > 1 || r[0] !== '');
}

function convertCSVToXMLSpreadsheet(csvRows) {
  const escapeXml = (unsafe) => {
    return unsafe.replace(/[<>&'"]/g, (c) => {
      switch (c) {
        case '<': return '&lt;';
        case '>': return '&gt;';
        case '&': return '&amp;';
        case '\'': return '&apos;';
        case '"': return '&quot;';
        default: return c;
      }
    });
  };

  let xml = '<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:html="http://www.w3.org/TR/REC-html40"><Worksheet ss:Name="Sheet1"><Table>';
  for (const row of csvRows) {
    xml += '<Row>';
    for (const cell of row) {
      xml += `<Cell><Data ss:Type="String">${escapeXml(cell)}</Data></Cell>`;
    }
    xml += '</Row>';
  }
  xml += '</Table></Worksheet></Workbook>';
  return xml;
}

function generatePDF(exportType, csvRows, user) {
  if (csvRows.length === 0) return null;
  const headers = csvRows[0];
  const body = csvRows.slice(1);

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42); // Sleek slate/dark color
  doc.text(`${exportType} Report`, 14, 15);

  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const generator = user?.userId || user?.email || 'Admin';
  doc.text(`Generated By: ${generator}`, 14, 21);
  doc.text(`Timestamp: ${new Date().toLocaleString()}`, 14, 26);
  doc.text(`Total Records: ${body.length}`, 14, 31);

  // AutoTable
  autoTable(doc, {
    startY: 36,
    head: [headers],
    body: body,
    theme: 'grid',
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8
    },
    styles: {
      fontSize: 8,
      cellPadding: 2,
      overflow: 'linebreak'
    },
    margin: { left: 14, right: 14 }
  });

  return doc;
}

export default function ReportsExport() {
  const { user } = useAuth();
  const [exportType, setExportType] = useState('Audit Log');
  const [exportFormat, setExportFormat] = useState('CSV');
  const [statusMsg, setStatusMsg] = useState('');

  const handleExport = async (e) => {
    e.preventDefault();
    setStatusMsg('Generating report...');
    
    const payload = {
      exportType,
      exportFormat,
      exportedBy: user?.userId || user?.email || "Admin"
    };

    try {
      const res = await fetch('http://localhost:8080/api/reports/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (res.ok) {
        const data = await res.json();
        if (data.csvData) {
          const rows = parseCSV(data.csvData);
          const baseFilename = (data.filename || 'report.csv').replace('.csv', '');

          if (exportFormat === 'PDF') {
            const doc = generatePDF(exportType, rows, user);
            if (doc) {
              const filename = `${baseFilename}.pdf`;
              doc.save(filename);
              setStatusMsg(`Success: Downloaded "${filename}" successfully.`);
            } else {
              setStatusMsg('Error: No data available to generate PDF.');
            }
          } else if (exportFormat === 'Excel') {
            const xmlContent = convertCSVToXMLSpreadsheet(rows);
            const blob = new Blob([xmlContent], { type: 'application/vnd.ms-excel;charset=utf-8;' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            const filename = `${baseFilename}.xls`;
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            setStatusMsg(`Success: Downloaded "${filename}" successfully.`);
          } else {
            // CSV
            const blob = new Blob([data.csvData], { type: 'text/csv;charset=utf-8;' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            const filename = `${baseFilename}.csv`;
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            setStatusMsg(`Success: Downloaded "${filename}" successfully.`);
          }
        } else {
          setStatusMsg('Success: ' + data.message + ' (Check Audit Logs)');
        }
      } else {
        setStatusMsg('Failed to export report: ' + await res.text());
      }
    } catch (e) {
      console.error(e);
      setStatusMsg(`Error exporting report: ${e.message || e}`);
    }
  };

  return (
    <div className="pam-container">
      <h1 style={{ textShadow: '0 2px 10px rgba(0,0,0,0.5)' }}>Export Reports</h1>
      
      <div className="pam-card" style={{ padding: '2rem', marginTop: '1rem', maxWidth: '500px' }}>
        <h3>Generate System Report</h3>
        <form onSubmit={handleExport} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', marginTop: '1.5rem' }}>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <label style={{ fontWeight: 'bold' }}>Report Type</label>
            <select 
              className="pam-select"
              value={exportType}
              onChange={(e) => setExportType(e.target.value)}
              style={{ color: '#000' }}
            >
              <option value="Server Inventory">Server Inventory</option>
              <option value="User List">User List</option>
              <option value="Ticket History">Ticket History</option>
              <option value="Access History">Access History</option>
              <option value="Audit Log">Audit Logs</option>
              <option value="Credential Inventory">Credential Inventory</option>
            </select>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <label style={{ fontWeight: 'bold' }}>Format</label>
            <select 
              className="pam-select"
              value={exportFormat}
              onChange={(e) => setExportFormat(e.target.value)}
              style={{ color: '#000' }}
            >
              <option value="CSV">CSV (.csv)</option>
              <option value="Excel">Excel (.xlsx)</option>
              <option value="PDF">PDF (.pdf)</option>
            </select>
          </div>

          <button className="pam-button" type="submit">
            Export Report
          </button>
        </form>

        {statusMsg && (
          <div style={{ marginTop: '1.5rem', padding: '1rem', background: 'rgba(255,255,255,0.1)', borderRadius: '8px', fontSize: '0.9rem' }}>
            {statusMsg}
          </div>
        )}
      </div>
    </div>
  );
}
